version: "3.3"
services:
    web:
        build: ./nginx
        ports:
            - "80:80"
        volumes:
            - ./www:/usr/share/nginx/content
        depends_on:
            - php
    php:
        build: ./php
        volumes:
            - ./www:/usr/share/nginx/content
        depends_on:
            - db
    db:
        build: ./db
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: password
